# Generated by Django 6.1 on 2026-08-25 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soporte', '0002_remove_cliente_telefono_cliente_apellido_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnostico', models.TextField(blank=True, default='')),
                ('fecha_entrega', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ESPERA', 'En espera'), ('REPARANDO', 'En reparación'), ('FINALIZADO', 'Finalizado'), ('ENTREGADO', 'Entregado')], default='ESPERA', max_length=20)),
                ('solucion', models.TextField(blank=True, default='')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='soporte.tecnico')),
            ],
        ),
    ]
